package com.example.crowdtransportfeedback.moderation;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*; import java.time.Instant; import java.util.*; import org.junit.jupiter.api.*; import org.mockito.ArgumentCaptor;
import com.example.crowdtransportfeedback.gamification.GamificationService; import com.example.crowdtransportfeedback.user.*;
class ReportLifecycleTest {
 FeedbackReportRepository reports=mock(FeedbackReportRepository.class);AdminAuditLogRepository audit=mock(AdminAuditLogRepository.class);UserRepository users=mock(UserRepository.class);GamificationService gamification=mock(GamificationService.class);ReportLifecycle lifecycle=new ReportLifecycle(reports,audit,users,gamification);UUID feedbackId=UUID.randomUUID(),adminId=UUID.randomUUID();AppUser admin=user(adminId,"admin1"),reporter=user(UUID.randomUUID(),"reporter1");
 @BeforeEach void setup(){when(users.getReferenceById(adminId)).thenReturn(admin);}
 @Test void keepDismissesAndAuditsWithoutProgress(){FeedbackReport report=pending();when(reports.findByFeedbackIdAndStatus(feedbackId,ReportStatus.PENDING)).thenReturn(List.of(report));lifecycle.resolve(feedbackId,adminId,false,"keep note");assertEquals(ReportStatus.DISMISSED,report.status);assertNotNull(report.resolvedAt);assertSame(admin,report.resolvedBy);verify(gamification,never()).evaluate(any(),any());assertAudit("REPORTS_DISMISSED","keep note");}
 @Test void deleteConfirmsAuditsAndEvaluatesReporterWithoutXp(){FeedbackReport report=pending();when(reports.findByFeedbackIdAndStatus(feedbackId,ReportStatus.PENDING)).thenReturn(List.of(report));lifecycle.resolve(feedbackId,adminId,true,"delete note");assertEquals(ReportStatus.CONFIRMED,report.status);assertNotNull(report.resolvedAt);assertSame(admin,report.resolvedBy);verify(gamification).evaluate(eq(reporter),any(Instant.class));verifyNoMoreInteractions(gamification);assertAudit("REPORTED_FEEDBACK_DELETED","delete note");}
 @Test void authorDeleteClosesWithoutProgressOrAudit(){FeedbackReport report=pending();when(reports.findByFeedbackIdAndStatus(feedbackId,ReportStatus.PENDING)).thenReturn(List.of(report));lifecycle.close(feedbackId);assertEquals(ReportStatus.CLOSED,report.status);assertNotNull(report.resolvedAt);assertNull(report.resolvedBy);verifyNoInteractions(gamification,audit);}
 @Test void directDeleteWithoutReportsWritesNormalAudit(){lifecycle.auditDelete(feedbackId,adminId);assertAudit("FEEDBACK_DELETED",null);}
 private FeedbackReport pending(){return new FeedbackReport(feedbackId,reporter,ReportReason.SPAM,null);} private void assertAudit(String action,String details){ArgumentCaptor<AdminAuditLog> c=ArgumentCaptor.forClass(AdminAuditLog.class);verify(audit).save(c.capture());assertEquals(action,c.getValue().action);assertEquals(details,c.getValue().details);assertEquals(feedbackId,c.getValue().targetId);}
 private static AppUser user(UUID id,String name){return new AppUser(id,name+"@example.com",name,"hash",Role.USER,Instant.now());}
}
