package com.example.crowdtransportfeedback.moderation;
import com.example.crowdtransportfeedback.common.ApiException; import com.example.crowdtransportfeedback.feedback.*; import com.example.crowdtransportfeedback.user.*; import java.time.Instant; import java.util.*; import org.junit.jupiter.api.*; import org.springframework.http.HttpStatus; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
class ReportServiceTest {
 FeedbackReportRepository reports=mock(FeedbackReportRepository.class);FeedbackRepository feedback=mock(FeedbackRepository.class);UserRepository users=mock(UserRepository.class);ReportService service=new ReportService(reports,feedback,users);UUID authorId=UUID.randomUUID(),reporterId=UUID.randomUUID(),feedbackId=UUID.randomUUID();
 @BeforeEach void item(){var author=new AppUser(authorId,"author@example.com","author1","hash",Role.USER,Instant.now());var f=new Feedback(feedbackId,author,TransportType.BUS,"100",3,4,5,"ok",44,26,System.currentTimeMillis());when(feedback.findById(feedbackId)).thenReturn(Optional.of(f));when(feedback.existsById(feedbackId)).thenReturn(true);when(users.getReferenceById(reporterId)).thenReturn(new AppUser(reporterId,"reporter@example.com","reporter1","hash",Role.USER,Instant.now()));when(reports.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void createsPendingReport(){var out=service.create(feedbackId,reporterId,new ReportDtos.CreateRequest(ReportReason.SPAM,null));assertEquals(ReportStatus.PENDING,out.status());}
 @Test void rejectsOwnReport(){assertEquals(HttpStatus.FORBIDDEN,assertThrows(ApiException.class,()->service.create(feedbackId,authorId,new ReportDtos.CreateRequest(ReportReason.SPAM,null))).status);}
 @Test void rejectsDuplicate(){when(reports.findByFeedbackIdAndReporterId(feedbackId,reporterId)).thenReturn(Optional.of(mock(FeedbackReport.class)));assertEquals(HttpStatus.CONFLICT,assertThrows(ApiException.class,()->service.create(feedbackId,reporterId,new ReportDtos.CreateRequest(ReportReason.SPAM,null))).status);}
 @Test void requiresExistingFeedback(){UUID absent=UUID.randomUUID();assertEquals(HttpStatus.NOT_FOUND,assertThrows(ApiException.class,()->service.create(absent,reporterId,new ReportDtos.CreateRequest(ReportReason.SPAM,null))).status);}
 @Test void otherRequiresDetails(){assertEquals(HttpStatus.BAD_REQUEST,assertThrows(ApiException.class,()->service.create(feedbackId,reporterId,new ReportDtos.CreateRequest(ReportReason.OTHER," "))).status);}
 @Test void detailsAreLimitedTo250Characters(){assertEquals(HttpStatus.BAD_REQUEST,assertThrows(ApiException.class,()->service.create(feedbackId,reporterId,new ReportDtos.CreateRequest(ReportReason.SPAM,"x".repeat(251)))).status);}
}
