package com.example.crowdtransportfeedback.analytics;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
import com.example.crowdtransportfeedback.feedback.*; import com.example.crowdtransportfeedback.user.*; import java.time.*; import java.util.*; import org.junit.jupiter.api.*;
class TrustAggregationServiceTest {
 static final Instant NOW=Instant.parse("2026-09-05T12:00:00Z"); FeedbackRepository repo=mock(FeedbackRepository.class); TrustAggregationService service=new TrustAggregationService(repo,Clock.fixed(NOW,ZoneOffset.UTC));
 AppUser user(int n){return new AppUser(new UUID(0,n),"u"+n+"@x.test","user"+n,"hash",Role.USER,NOW);}
 Feedback row(int n,AppUser u,int score,long ageHours){return new Feedback(new UUID(1,n),u,TransportType.METRO,"M2",score,score,score,"",44.4268,26.1025,NOW.minus(Duration.ofHours(ageHours)).toEpochMilli());}
 @Test void freshFiveUsesNeutralPrior(){assertEquals(3.6667,service.aggregate(List.of(row(1,user(1),5,0)),f->f.score),.001);}
 @Test void thirtyDayHalfLifeIsApplied(){double v=service.aggregate(List.of(row(1,user(1),5,720)),f->f.score);assertEquals((6+2.5)/2.5,v,.001);}
 @Test void manyRowsFromOneUserDoNotEqualIndependentUsers(){AppUser one=user(1);List<Feedback> repeated=new ArrayList<>();for(int i=0;i<20;i++)repeated.add(row(i,one,5,0));double oneScore=service.aggregate(repeated,f->f.score);assertEquals(3.6667,oneScore,.001);assertTrue(service.aggregate(List.of(row(30,user(1),5,0),row(31,user(2),5,0)),f->f.score)>oneScore);}
 @Test void filtersWindowsMetricsConfidenceAndLatestFive(){List<Feedback> rows=new ArrayList<>();for(int i=0;i<7;i++)rows.add(row(i,user(i+1),(i%5)+1,i));rows.add(new Feedback(new UUID(2,1),user(8),TransportType.BUS,"100",5,5,5,"",44.4268,26.1025,NOW.minus(Duration.ofDays(31)).toEpochMilli()));when(repo.findAll()).thenReturn(rows);var cells=service.heatmap(AnalyticsMetric.CROWDING,TransportType.METRO," m2 ",AnalyticsWindow.H24);assertEquals(1,cells.size());assertEquals(7,cells.getFirst().feedbackCount());assertEquals(ConfidenceLevel.HIGH,cells.getFirst().confidence());var area=service.area(cells.getFirst().cellId(),AnalyticsMetric.TRUST,TransportType.METRO,"M2",AnalyticsWindow.D30);assertEquals(5,area.latestFeedbacks().size());assertEquals("user1",area.latestFeedbacks().getFirst().createdByUsername());assertTrue(area.latestFeedbacks().get(0).createdAt()>area.latestFeedbacks().get(1).createdAt());}
 @Test void cutoffIsInclusiveAndFutureExcluded(){when(repo.findAll()).thenReturn(List.of(row(1,user(1),5,24),row(2,user(2),1,25),new Feedback(new UUID(3,1),user(3),TransportType.METRO,"M2",5,5,5,"",44.4268,26.1025,NOW.plusSeconds(1).toEpochMilli())));assertEquals(1,service.heatmap(AnalyticsMetric.PUNCTUALITY,null,null,AnalyticsWindow.H24).getFirst().feedbackCount());}
 @Test void noDataAndConfidenceThresholds(){when(repo.findAll()).thenReturn(List.of());assertTrue(service.heatmap(AnalyticsMetric.CLEANLINESS,null,null,AnalyticsWindow.ALL).isEmpty());assertEquals(ConfidenceLevel.NONE,ConfidenceLevel.of(0));assertEquals(ConfidenceLevel.LOW,ConfidenceLevel.of(2));assertEquals(ConfidenceLevel.MEDIUM,ConfidenceLevel.of(5));assertEquals(ConfidenceLevel.HIGH,ConfidenceLevel.of(6));}
}
