package com.example.crowdtransportfeedback.ui.screens
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import com.example.crowdtransportfeedback.admin.*
import kotlinx.coroutines.launch

@Composable fun AdminDashboardScreen(api:AdminApi){
 val tabs=listOf("Overview","Reports","Feedback","Users","Reporting");var selected by remember{mutableIntStateOf(0)}
 Column(Modifier.fillMaxSize()){Text("Admin Dashboard",style=MaterialTheme.typography.headlineSmall,modifier=Modifier.padding(16.dp));ScrollableTabRow(selectedTabIndex=selected){tabs.forEachIndexed{i,t->Tab(selected==i,onClick={selected=i},text={Text(t)})}};when(selected){0->OverviewTab(api);1->ReportsTab(api);2->FeedbackTab(api);3->UsersTab(api);else->ReportingTab(api)}}
}
@Composable private fun <T> OnlinePanel(load:suspend()->T,content:@Composable(T)->Unit){var value by remember{mutableStateOf<T?>(null)};var error by remember{mutableStateOf(false)};var refresh by remember{mutableIntStateOf(0)};LaunchedEffect(refresh){error=false;runCatching{load()}.onSuccess{value=it}.onFailure{error=true}};when{error->Column(Modifier.padding(16.dp)){Text("Admin dashboard requires a connection.");Button({refresh++}){Text("Try again")}};value==null->Box(Modifier.fillMaxSize().padding(24.dp)){CircularProgressIndicator()};else->content(value!!)}}
@Composable private fun OverviewTab(api:AdminApi)=OnlinePanel({api.overview()}){o->LazyColumn(Modifier.padding(16.dp)){item{Text("Users: ${o.totalUsers}");Text("Feedback: ${o.totalFeedbacks}");Text("Last 24h / 7d / 30d: ${o.feedbackLast24h} / ${o.feedbackLast7d} / ${o.feedbackLast30d}");Text("Active contributors (30d): ${o.activeContributors30d}");Text("Pending reports: ${o.pendingReports} across ${o.reportedFeedbackAwaitingReview} feedbacks");Spacer(Modifier.height(12.dp));Text("Top lines",style=MaterialTheme.typography.titleMedium);o.topLines.forEach{Text("${it.transportType} / ${it.line} — ${it.count}")}}}}
@Composable private fun ReportsTab(api:AdminApi){var refresh by remember{mutableIntStateOf(0)};key(refresh){OnlinePanel({api.reports()}){p->if(p.content.isEmpty())Text("No feedback awaiting review",Modifier.padding(16.dp))else LazyColumn{items(p.content,key={it.feedbackId}){r->var confirm by remember{mutableStateOf(false)};Card(Modifier.fillMaxWidth().padding(8.dp)){Column(Modifier.padding(12.dp)){Text("${r.transportType} / ${r.line}",style=MaterialTheme.typography.titleMedium);Text("@${r.authorUsername} · ${r.reportCount} pending reports");Text(r.reasonCounts.entries.joinToString{ "${it.key}: ${it.value}" });var detail by remember{mutableStateOf<ModerationDetail?>(null)};TextButton({kotlinx.coroutines.MainScope().launch{detail=runCatching{api.detail(r.feedbackId)}.getOrNull()}}){Text("Inspect reports")};detail?.let{d->d.reports.forEach{Text("@${it.reporterUsername}: ${it.reason}${it.details?.let{v->" — $v"}.orEmpty()}")}};Row{Button({kotlinx.coroutines.MainScope().launch{api.resolve(r.feedbackId,ResolveRequest("KEEP"));refresh++}}){Text("Keep")};Spacer(Modifier.width(8.dp));Button({confirm=true},colors=ButtonDefaults.buttonColors(containerColor=MaterialTheme.colorScheme.error)){Text("Delete")}}};if(confirm)AlertDialog(onDismissRequest={confirm=false},title={Text("Delete reported feedback?")},text={Text("This confirms all pending reports and cannot be undone.")},confirmButton={Button({kotlinx.coroutines.MainScope().launch{api.resolve(r.feedbackId,ResolveRequest("DELETE"));confirm=false;refresh++}}){Text("Delete")}},dismissButton={TextButton({confirm=false}){Text("Cancel")}})}}}}}}
@Composable private fun FeedbackTab(api:AdminApi)=OnlinePanel({api.feedback()}){p->if(p.content.isEmpty())Text("No feedback",Modifier.padding(16.dp))else LazyColumn{items(p.content){f->ListItem(headlineContent={Text("${f.transportType} / ${f.line} · ${f.score}")},supportingContent={Text("@${f.username}${f.comment?.let{" — $it"}.orEmpty()}")})}}}
@Composable private fun UsersTab(api:AdminApi)=OnlinePanel({api.users()}){p->if(p.content.isEmpty())Text("No users",Modifier.padding(16.dp))else LazyColumn{items(p.content){u->ListItem(headlineContent={Text("@${u.username} · ${u.role}")},supportingContent={Text("${u.feedbackCount} feedback · ${u.totalXp} XP · level ${u.level} · ${u.verifiedReportCount} verified reports")})}}}
@Composable private fun ReportingTab(api:AdminApi){val context=LocalContext.current;var csv by remember{mutableStateOf<ByteArray?>(null)};val launcher=rememberLauncherForActivityResult(ActivityResultContracts.CreateDocument("text/csv")){uri->uri?.let{context.contentResolver.openOutputStream(it)?.use{o->csv?.let { bytes -> o.write(bytes) }}}};val scope=rememberCoroutineScope();OnlinePanel({api.summary()}){s->Column(Modifier.padding(16.dp)){Text("Feedback: ${s.feedbackCount}");Text("Unique contributors: ${s.uniqueContributors}");Text("Average overall: ${s.averageOverall ?: "—"}");Text("Punctuality / cleanliness / crowding: ${s.averagePunctuality ?: "—"} / ${s.averageCleanliness ?: "—"} / ${s.averageCrowding ?: "—"}");Text("Most active: ${s.mostActiveTransportType ?: "—"} · ${s.mostActiveLine ?: "—"}");Spacer(Modifier.height(16.dp));Button({scope.launch{runCatching{api.csv().bytes()}.onSuccess{csv=it;launcher.launch("feedback-export.csv")}}}){Text("Export CSV")}}}}
