package com.example.crowdtransportfeedback.admin;
import com.example.crowdtransportfeedback.common.ApiException; import com.example.crowdtransportfeedback.feedback.*; import com.example.crowdtransportfeedback.gamification.LevelCatalog; import com.example.crowdtransportfeedback.moderation.*;
import java.nio.charset.StandardCharsets; import java.sql.*; import java.time.*; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class AdminService {
 private final JdbcTemplate db; private final FeedbackService feedback; private final ReportLifecycle lifecycle;
 public AdminService(JdbcTemplate d,FeedbackService f,ReportLifecycle l){db=d;feedback=f;lifecycle=l;}
 private long scalar(String sql,Object... args){Long n=db.queryForObject(sql,Long.class,args);return n==null?0:n;}
 @Transactional(readOnly=true) public AdminDtos.Overview overview(){long now=System.currentTimeMillis();Map<String,Long> types=new LinkedHashMap<>();db.query("select transport_type,count(*) from feedback group by transport_type",r->{types.put(r.getString(1),r.getLong(2));});var top=db.query("select transport_type,line,count(*) c from feedback group by transport_type,line order by c desc,transport_type,line limit 5",(r,n)->new AdminDtos.TopLine(r.getString(1),r.getString(2),r.getLong(3)));return new AdminDtos.Overview(scalar("select count(*) from app_user"),scalar("select count(*) from feedback"),scalar("select count(*) from feedback where created_at>=?",now-86400000L),scalar("select count(*) from feedback where created_at>=?",now-604800000L),scalar("select count(*) from feedback where created_at>=?",now-2592000000L),scalar("select count(distinct created_by_user_id) from feedback where created_at>=?",now-2592000000L),scalar("select count(*) from feedback_report where status='PENDING'"),scalar("select count(distinct feedback_id) from feedback_report where status='PENDING'"),types,top);}
 @Transactional(readOnly=true) public AdminDtos.Page<AdminDtos.QueueItem> queue(int page,int size){page=page(page);size=size(size);long total=scalar("select count(distinct feedback_id) from feedback_report where status='PENDING'");String sql="select f.feedback_id,u.username,f.transport_type,f.line,f.score,max(r.created_at) last_at,count(*) reports from feedback_report r join feedback f on f.feedback_id=r.feedback_id join app_user u on u.id=f.created_by_user_id where r.status='PENDING' group by f.feedback_id,u.username,f.transport_type,f.line,f.score order by last_at desc limit ? offset ?";var rows=db.query(sql,(rs,n)->new AdminDtos.QueueItem(UUID.fromString(rs.getString(1)),rs.getString(2),rs.getString(3),rs.getString(4),rs.getDouble(5),rs.getLong(7),rs.getTimestamp(6).toInstant(),reasonCounts(UUID.fromString(rs.getString(1)))),size,(long)page*size);return page(rows,page,size,total);}
 private Map<String,Long> reasonCounts(UUID id){Map<String,Long> out=new LinkedHashMap<>();db.query("select reason,count(*) from feedback_report where feedback_id=? and status='PENDING' group by reason",r->{out.put(r.getString(1),r.getLong(2));},id);return out;}
 @Transactional(readOnly=true) public AdminDtos.ModerationDetail detail(UUID id){var item=feedback.get(id);var reports=db.query("select r.id,u.username,r.reason,r.details,r.created_at from feedback_report r join app_user u on u.id=r.reporter_user_id where r.feedback_id=? and r.status='PENDING' order by r.created_at",(r,n)->new AdminDtos.PendingReport(UUID.fromString(r.getString(1)),r.getString(2),r.getString(3),r.getString(4),r.getTimestamp(5).toInstant()),id);if(reports.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"pending_reports_not_found","No pending reports exist for this feedback");return new AdminDtos.ModerationDetail(item,reports);}
 @Transactional public void resolve(UUID id,UUID admin,AdminDtos.ResolveRequest request){if(request==null||request.action()==null)throw badAction();String action=request.action().trim().toUpperCase(Locale.ROOT);if(action.equals("KEEP")){if(!feedbackExists(id)||!lifecycle.hasPending(id))throw new ApiException(HttpStatus.NOT_FOUND,"pending_reports_not_found","No pending reports exist for this feedback");lifecycle.resolve(id,admin,false,cleanNote(request.note()));}else if(action.equals("DELETE")){if(!lifecycle.hasPending(id))throw new ApiException(HttpStatus.NOT_FOUND,"pending_reports_not_found","No pending reports exist for this feedback");feedback.delete(id,admin,"ADMIN",cleanNote(request.note()));}else throw badAction();}
 private ApiException badAction(){return new ApiException(HttpStatus.BAD_REQUEST,"invalid_moderation_action","Action must be KEEP or DELETE");} private boolean feedbackExists(UUID id){try{feedback.get(id);return true;}catch(ApiException e){return false;}}
 @Transactional(readOnly=true) public AdminDtos.Page<AdminDtos.AdminFeedback> feedbackList(String type,String line,String window,String username,int page,int size){page=page(page);size=size(size);List<Object>a=new ArrayList<>();String where=where(type,line,window,username,a);long total=scalar("select count(*) from feedback f join app_user u on u.id=f.created_by_user_id "+where,a.toArray());a.add(size);a.add((long)page*size);var rows=db.query("select f.feedback_id,f.created_at,u.username,f.transport_type,f.line,f.score,f.comment from feedback f join app_user u on u.id=f.created_by_user_id "+where+" order by f.created_at desc limit ? offset ?",(r,n)->new AdminDtos.AdminFeedback(UUID.fromString(r.getString(1)),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getDouble(6),r.getString(7)),a.toArray());return page(rows,page,size,total);}
 @Transactional(readOnly=true) public AdminDtos.Page<AdminDtos.AdminUser> users(String query,int page,int size){page=page(page);size=size(size);String q=query==null?"%":"%"+query.trim().toLowerCase(Locale.ROOT)+"%";long total=scalar("select count(*) from app_user where lower(username) like ?",q);String sql="select u.id,u.username,u.role,u.created_at,(select count(*) from feedback f where f.created_by_user_id=u.id),(select coalesce(sum(g.xp_delta),0) from gamification_event g where g.user_id=u.id),(select count(*) from feedback_report r where r.reporter_user_id=u.id and r.status='CONFIRMED') from app_user u where lower(u.username) like ? group by u.id order by u.username limit ? offset ?";var rows=db.query(sql,(r,n)->{long xp=r.getLong(6);return new AdminDtos.AdminUser(UUID.fromString(r.getString(1)),r.getString(2),r.getString(3),r.getTimestamp(4).toInstant(),r.getLong(5),xp,level(xp),r.getLong(7));},q,size,(long)page*size);return page(rows,page,size,total);}
 @Transactional(readOnly=true) public AdminDtos.ReportingSummary summary(String window,String type,String line){List<Object>a=new ArrayList<>();String where=where(type,line,window,null,a);var base=db.queryForMap("select count(*) count,count(distinct created_by_user_id) contributors,avg(score) overall,avg(punctuality_score) punctuality,avg(cleanliness_score) cleanliness,avg(crowding_score) crowding from feedback f "+where,a.toArray());String topType=top("select transport_type from feedback f "+where+" group by transport_type order by count(*) desc limit 1",a);String topLine=top("select transport_type||' / '||line from feedback f "+where+" group by transport_type,line order by count(*) desc limit 1",a);return new AdminDtos.ReportingSummary(num(base,"count"),num(base,"contributors"),decimal(base,"overall"),decimal(base,"punctuality"),decimal(base,"cleanliness"),decimal(base,"crowding"),topType,topLine);}
 @Transactional(readOnly=true) public byte[] csv(String window,String type,String line){List<Object>a=new ArrayList<>();String where=where(type,line,window,null,a);StringBuilder b=new StringBuilder("feedback_id,created_at,username,transport_type,line,overall_score,punctuality,cleanliness,crowding,latitude,longitude,comment\r\n");db.query("select f.feedback_id,f.created_at,u.username,f.transport_type,f.line,f.score,f.punctuality_score,f.cleanliness_score,f.crowding_score,f.latitude,f.longitude,f.comment from feedback f join app_user u on u.id=f.created_by_user_id "+where+" order by f.created_at",r->{for(int i=1;i<=12;i++){if(i>1)b.append(',');b.append(csvCell(r.getObject(i)));}b.append("\r\n");},a.toArray());return b.toString().getBytes(StandardCharsets.UTF_8);}
 private String where(String type,String line,String window,String username,List<Object>a){List<String>w=new ArrayList<>();if(type!=null&&!type.isBlank()){w.add("f.transport_type=?");a.add(type.trim().toUpperCase(Locale.ROOT));}if(line!=null&&!line.isBlank()){w.add("f.normalized_line=?");a.add(line.trim().toUpperCase(Locale.ROOT));}if(username!=null&&!username.isBlank()){w.add("lower(u.username)=?");a.add(username.trim().toLowerCase(Locale.ROOT));}long d=switch(window==null?"ALL":window.toUpperCase(Locale.ROOT)){case "D1"->1;case "D7"->7;case "D30"->30;case "ALL"->0;default->throw new ApiException(HttpStatus.BAD_REQUEST,"invalid_window","Window must be D1, D7, D30 or ALL");};if(d>0){w.add("f.created_at>=?");a.add(System.currentTimeMillis()-d*86400000L);}return w.isEmpty()?"":"where "+String.join(" and ",w);}
 private String top(String sql,List<Object>a){var x=db.query(sql,(r,n)->r.getString(1),a.toArray());return x.isEmpty()?null:x.get(0);} private long num(Map<String,Object>m,String k){Object n=m.get(k);return n==null?0:((Number)n).longValue();}private Double decimal(Map<String,Object>m,String k){Object n=m.get(k);return n==null?null:((Number)n).doubleValue();}private String cleanNote(String n){if(n==null)return null;n=n.trim();return n.isEmpty()?null:n.substring(0,Math.min(1000,n.length()));}private int page(int p){if(p<0)throw new ApiException(HttpStatus.BAD_REQUEST,"invalid_page","Page cannot be negative");return p;}private int size(int s){if(s<1||s>100)throw new ApiException(HttpStatus.BAD_REQUEST,"invalid_size","Size must be between 1 and 100");return s;}private <T> AdminDtos.Page<T> page(List<T>x,int p,int s,long total){return new AdminDtos.Page<>(x,p,s,total,(int)Math.ceil(total/(double)s));}private int level(long xp){return LevelCatalog.forXp(xp).level();}private String csvCell(Object v){if(v==null)return "";String s=String.valueOf(v);return '"'+s.replace("\"","\"\"")+'"';}
}
