package com.example.crowdtransportfeedback.admin;
import static org.mockito.Mockito.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.example.crowdtransportfeedback.common.ApiExceptionHandler; import com.example.crowdtransportfeedback.security.*; import java.util.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest; import org.springframework.boot.test.mock.mockito.MockBean; import org.springframework.context.annotation.Import; import org.springframework.test.web.servlet.MockMvc;
@WebMvcTest(AdminController.class) @Import({SecurityConfig.class,JwtAuthenticationFilter.class,ApiExceptionHandler.class}) class AdminControllerSecurityTest {
 @Autowired MockMvc mvc; @MockBean AdminService service; @MockBean JwtService jwt;
 @BeforeEach void setup(){when(jwt.parse("user-token")).thenReturn(new JwtService.AuthenticatedUser(UUID.randomUUID(),"USER"));when(jwt.parse("admin-token")).thenReturn(new JwtService.AuthenticatedUser(UUID.randomUUID(),"ADMIN"));when(service.overview()).thenReturn(new AdminDtos.Overview(0,0,0,0,0,0,0,0,Map.of(),List.of()));}
 @Test void userIsForbiddenFromAdminNamespace()throws Exception{mvc.perform(get("/api/admin/overview").header("Authorization","Bearer user-token")).andExpect(status().isForbidden());verify(service,never()).overview();}
 @Test void adminPassesAuthorization()throws Exception{mvc.perform(get("/api/admin/overview").header("Authorization","Bearer admin-token")).andExpect(status().isOk());verify(service).overview();}
 @Test void feedbackFiltersAndPaginationAreForwarded()throws Exception{when(service.feedbackList("BUS","100","D7","alice",2,10)).thenReturn(new AdminDtos.Page<>(List.of(),2,10,21,3));mvc.perform(get("/api/admin/feedback?transportType=BUS&line=100&window=D7&username=alice&page=2&size=10").header("Authorization","Bearer admin-token")).andExpect(status().isOk()).andExpect(jsonPath("$.page").value(2)).andExpect(jsonPath("$.totalPages").value(3));verify(service).feedbackList("BUS","100","D7","alice",2,10);}
 @Test void userSearchAndPaginationAreForwarded()throws Exception{when(service.users("ali",1,5)).thenReturn(new AdminDtos.Page<>(List.of(),1,5,6,2));mvc.perform(get("/api/admin/users?query=ali&page=1&size=5").header("Authorization","Bearer admin-token")).andExpect(status().isOk()).andExpect(jsonPath("$.totalElements").value(6));verify(service).users("ali",1,5);}
 @Test void reportingAndCsvUseFiltersAndHeaders()throws Exception{when(service.summary("D30","METRO","M2")).thenReturn(new AdminDtos.ReportingSummary(1,1,4d,4d,4d,4d,"METRO","METRO / M2"));when(service.csv("D30","METRO","M2")).thenReturn("feedback_id,created_at\r\n".getBytes());mvc.perform(get("/api/admin/reporting/summary?window=D30&transportType=METRO&line=M2").header("Authorization","Bearer admin-token")).andExpect(status().isOk()).andExpect(jsonPath("$.feedbackCount").value(1));mvc.perform(get("/api/admin/reporting/feedback.csv?window=D30&transportType=METRO&line=M2").header("Authorization","Bearer admin-token")).andExpect(status().isOk()).andExpect(header().string("Content-Disposition","attachment; filename=feedback-export.csv")).andExpect(content().contentType("text/csv;charset=UTF-8")).andExpect(content().string("feedback_id,created_at\r\n"));}
}
