package com.example.crowdtransportfeedback.profile;
import com.example.crowdtransportfeedback.common.ApiException; import com.example.crowdtransportfeedback.gamification.*; import com.example.crowdtransportfeedback.user.*; import java.time.*; import java.util.*; import java.util.stream.Collectors; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ProfileService {
 private static final Set<String> AVATARS=Set.of("COMMUTER","NAVIGATOR","EXPLORER"); private final UserRepository users; private final GamificationEventRepository events; private final UserAchievementRepository unlocked; private final JdbcTemplate jdbc;
 public ProfileService(UserRepository u,GamificationEventRepository e,UserAchievementRepository a,JdbcTemplate j){users=u;events=e;unlocked=a;jdbc=j;}
 @Transactional(readOnly=true) public ProfileDtos.MyProfile me(UUID id){AppUser u=user(id);var p=publicProfile(u.username);Map<String,Long>b=new LinkedHashMap<>();jdbc.query("select transport_type,count(*) from feedback where created_by_user_id=? group by transport_type",rs->{b.put(rs.getString(1),rs.getLong(2));},id);Long rank=jdbc.queryForObject("select r from (select id,row_number() over(order by xp desc,username) r from (select u.id,u.username,coalesce(sum(e.xp_delta),0) xp from app_user u left join gamification_event e on e.user_id=u.id group by u.id,u.username) x) z where id=?",Long.class,id);return new ProfileDtos.MyProfile(p.username(),p.avatarKey(),p.totalXp(),p.level(),p.contributionCount(),p.differentLineCount(),p.transportTypeCount(),p.unlockedAchievementCount(),AchievementCatalog.ALL.size(),rank,p.pinnedAchievements(),b);}
 @Transactional(readOnly=true) public ProfileDtos.PublicProfile publicProfile(String username){AppUser u=users.findByUsername(username).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"profile_not_found","Profile was not found"));long xp=events.total(u.id);var stats=jdbc.queryForMap("select count(*) contributions,count(distinct transport_type||':'||normalized_line) lines,count(distinct transport_type) types from feedback where created_by_user_id=?",u.id);return new ProfileDtos.PublicProfile(u.username,u.avatarKey,xp,level(xp),n(stats,"contributions"),n(stats,"lines"),n(stats,"types"),unlocked.countByUserId(u.id),badges(u.id,true));}
 @Transactional(readOnly=true) public List<ProfileDtos.Badge> achievements(UUID id){return badges(id,false);}
 @Transactional public void avatar(UUID id,String key){if(!AVATARS.contains(key))throw new ApiException(HttpStatus.BAD_REQUEST,"invalid_avatar","Avatar must be COMMUTER, NAVIGATOR, or EXPLORER");user(id).avatarKey=key;}
 @Transactional public void pins(UUID id,List<String> codes){if(codes==null)codes=List.of();if(codes.size()>3||new HashSet<>(codes).size()!=codes.size())throw new ApiException(HttpStatus.BAD_REQUEST,"invalid_pins","Choose up to three distinct achievements");for(String c:codes)if(!unlocked.existsByUserIdAndCode(id,c))throw new ApiException(HttpStatus.BAD_REQUEST,"achievement_locked","Only unlocked achievements can be pinned");jdbc.update("delete from pinned_achievement where user_id=?",id);for(int i=0;i<codes.size();i++)jdbc.update("insert into pinned_achievement(user_id,achievement_code,display_order) values(?,?,?)",id,codes.get(i),i);}
 private List<ProfileDtos.Badge> badges(UUID id,boolean pinnedOnly){var rows=jdbc.query("select achievement_code,unlocked_at from user_achievement where user_id=?",rs->{Map<String,Instant>m=new HashMap<>();while(rs.next())m.put(rs.getString(1),rs.getTimestamp(2).toInstant());return m;},id);var pins=jdbc.query("select achievement_code from pinned_achievement where user_id=? order by display_order",(rs,n)->rs.getString(1),id);var stats=jdbc.queryForMap("select count(*) contributions,count(distinct transport_type||':'||normalized_line) lines,count(distinct transport_type) types,count(distinct (to_timestamp(created_at/1000.0) at time zone 'UTC')::date) days from feedback where created_by_user_id=?",id);Map<String,Long> typeCounts=jdbc.query("select transport_type,count(*) c from feedback where created_by_user_id=? group by transport_type",rs->{Map<String,Long>m=new HashMap<>();while(rs.next())m.put(rs.getString(1),rs.getLong(2));return m;},id);return AchievementCatalog.ALL.stream().filter(d->!pinnedOnly||pins.contains(d.code())).sorted(Comparator.comparingInt(d->{int x=pins.indexOf(d.code());return x<0?99:x;})).map(d->{long progress=switch(d.kind()){case CONTRIBUTIONS->n(stats,"contributions");case LINES->n(stats,"lines");case TYPES->n(stats,"types");case ACTIVE_DAYS->n(stats,"days");case TYPE_COUNT->typeCounts.getOrDefault(d.type(),0L);};return new ProfileDtos.Badge(d.code(),d.title(),d.description(),d.category(),rows.containsKey(d.code()),rows.get(d.code()),Math.min(progress,d.target()),d.target(),pins.contains(d.code()));}).toList();}
 private ProfileDtos.Level level(long xp){var l=LevelCatalog.forXp(xp);return new ProfileDtos.Level(l.level(),l.title(),xp-l.threshold(),LevelCatalog.nextThreshold(xp),l.level()==15);} private AppUser user(UUID id){return users.findById(id).orElseThrow();} private long n(Map<String,Object>m,String k){return ((Number)m.get(k)).longValue();}
}
