package com.example.crowdtransportfeedback.leaderboard;
import com.example.crowdtransportfeedback.common.ApiException; import com.example.crowdtransportfeedback.gamification.LevelCatalog; import com.example.crowdtransportfeedback.security.JwtService.AuthenticatedUser; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/leaderboard") public class LeaderboardController {
 enum Metric{XP,ACHIEVEMENTS,CONTRIBUTIONS} enum Period{ALL_TIME,THIS_MONTH}
 public record Entry(Long rank,String username,String avatarKey,int level,long metricValue,long totalXp,boolean currentUser){} public record Response(List<Entry> top,Entry currentUser){}
 private final JdbcTemplate jdbc; public LeaderboardController(JdbcTemplate j){jdbc=j;}
 @GetMapping Response get(@RequestParam(defaultValue="XP") Metric metric,@RequestParam(defaultValue="ALL_TIME") Period period,@RequestParam(defaultValue="100") int limit,@AuthenticationPrincipal AuthenticatedUser user){if(limit<1||limit>100)throw new ApiException(HttpStatus.BAD_REQUEST,"invalid_limit","Limit must be between 1 and 100");String measure=measure(metric,period);String order=metric==Metric.XP?"metric_value desc,username asc":"metric_value desc,total_xp desc,username asc";String sql="with values_ as (select u.id,u.username,u.avatar_key,coalesce((select sum(xp_delta) from gamification_event e where e.user_id=u.id),0) total_xp,"+measure+" metric_value from app_user u), ranked as (select *,case when metric_value=0 and ?='THIS_MONTH' then null else row_number() over(order by "+order+") end rank from values_) select rank,username,avatar_key,metric_value,total_xp,id from ranked";List<Entry>all=jdbc.query(sql,(rs,n)->new Entry((Long)rs.getObject("rank"),rs.getString("username"),rs.getString("avatar_key"),LevelCatalog.forXp(rs.getLong("total_xp")).level(),rs.getLong("metric_value"),rs.getLong("total_xp"),user.id().equals(rs.getObject("id",UUID.class))),period.name());Entry mine=all.stream().filter(Entry::currentUser).findFirst().orElseThrow();return new Response(all.stream().filter(e->e.rank()!=null&&e.rank()<=limit).toList(),mine);}
 private String measure(Metric m,Period p){String month="date_trunc('month',current_timestamp at time zone 'UTC')";return switch(m){case XP->"coalesce((select sum(xp_delta) from gamification_event e where e.user_id=u.id"+(p==Period.THIS_MONTH?" and e.created_at >= "+month+" at time zone 'UTC'":"")+"),0)";case ACHIEVEMENTS->"(select count(*) from user_achievement a where a.user_id=u.id"+(p==Period.THIS_MONTH?" and a.unlocked_at >= "+month+" at time zone 'UTC'":"")+")";case CONTRIBUTIONS->"(select count(*) from feedback f where f.created_by_user_id=u.id"+(p==Period.THIS_MONTH?" and to_timestamp(f.created_at/1000.0) >= "+month+" at time zone 'UTC'":"")+")";};}
}
