package com.example.crowdtransportfeedback.leaderboard;
import com.example.crowdtransportfeedback.common.ApiException; import com.example.crowdtransportfeedback.gamification.LevelCatalog; import com.example.crowdtransportfeedback.security.JwtService.AuthenticatedUser; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/leaderboard") public class LeaderboardController {
 enum Metric{XP,ACHIEVEMENTS,CONTRIBUTIONS} enum Period{ALL_TIME,THIS_MONTH}
 public record Entry(Long rank,String username,String avatarKey,int level,long metricValue,long totalXp,boolean currentUser){} public record Response(List<Entry> top,Entry currentUser){}
 private final JdbcTemplate jdbc; public LeaderboardController(JdbcTemplate j){jdbc=j;}
 @GetMapping Response get(@RequestParam(defaultValue="XP") Metric metric,@RequestParam(defaultValue="ALL_TIME") Period period,@RequestParam(defaultValue="100") int limit,@AuthenticationPrincipal AuthenticatedUser user){if(limit<1||limit>100)throw new ApiException(HttpStatus.BAD_REQUEST,"invalid_limit","Limit must be between 1 and 100");String sql="select u.id,u.username,u.avatar_key,coalesce((select sum(xp_delta) from gamification_event e where e.user_id=u.id),0) total_xp,"+measure(metric,period)+" metric_value from app_user u";List<LeaderboardRanking.Candidate> values=jdbc.query(sql,(rs,n)->new LeaderboardRanking.Candidate(rs.getObject("id",UUID.class),rs.getString("username"),rs.getString("avatar_key"),rs.getLong("metric_value"),rs.getLong("total_xp")));return LeaderboardRanking.rank(values,metric,period,limit,user.id());}
 private String measure(Metric m,Period p){String month="date_trunc('month',current_timestamp at time zone 'UTC')";String next="("+month+" + interval '1 month')";return switch(m){case XP->"coalesce((select sum(xp_delta) from gamification_event e where e.user_id=u.id"+(p==Period.THIS_MONTH?" and e.created_at >= "+month+" at time zone 'UTC' and e.created_at < "+next+" at time zone 'UTC'":"")+"),0)";case ACHIEVEMENTS->"(select count(*) from user_achievement a where a.user_id=u.id"+(p==Period.THIS_MONTH?" and a.unlocked_at >= "+month+" at time zone 'UTC' and a.unlocked_at < "+next+" at time zone 'UTC'":"")+")";case CONTRIBUTIONS->"(select count(*) from feedback f where f.created_by_user_id=u.id"+(p==Period.THIS_MONTH?" and to_timestamp(f.created_at/1000.0) >= "+month+" at time zone 'UTC' and to_timestamp(f.created_at/1000.0) < "+next+" at time zone 'UTC'":"")+")";};}
}
