package com.example.crowdtransportfeedback.gamification;
import java.util.List;
public final class AchievementCatalog {
 public record Definition(String code,String title,String description,String category,Kind kind,int target,String type){}
 public enum Kind { CONTRIBUTIONS,LINES,TYPES,TYPE_COUNT,ACTIVE_DAYS }
 public static final List<Definition> ALL=List.of(
  d("FIRST_CONTRIBUTION","First Contribution","Submit your first feedback","Contribution",Kind.CONTRIBUTIONS,1,null),d("GETTING_STARTED","Getting Started","Submit 5 feedbacks","Contribution",Kind.CONTRIBUTIONS,5,null),d("CONTRIBUTOR","Contributor","Submit 10 feedbacks","Contribution",Kind.CONTRIBUTIONS,10,null),d("REGULAR_CONTRIBUTOR","Regular Contributor","Submit 25 feedbacks","Contribution",Kind.CONTRIBUTIONS,25,null),d("DEDICATED_CONTRIBUTOR","Dedicated Contributor","Submit 50 feedbacks","Contribution",Kind.CONTRIBUTIONS,50,null),d("EXPERIENCED_CONTRIBUTOR","Experienced Contributor","Submit 100 feedbacks","Contribution",Kind.CONTRIBUTIONS,100,null),d("VETERAN_CONTRIBUTOR","Veteran Contributor","Submit 250 feedbacks","Contribution",Kind.CONTRIBUTIONS,250,null),
  d("ROUTE_STARTER","Route Starter","Contribute on 5 lines","Network Exploration",Kind.LINES,5,null),d("LINE_EXPLORER","Line Explorer","Contribute on 10 lines","Network Exploration",Kind.LINES,10,null),d("NETWORK_EXPLORER","Network Explorer","Contribute on 25 lines","Network Exploration",Kind.LINES,25,null),d("CITY_MAPPER","City Mapper","Contribute on 50 lines","Network Exploration",Kind.LINES,50,null),d("MULTIMODAL_EXPLORER","Multimodal Explorer","Contribute on all five transport types","Network Exploration",Kind.TYPES,5,null),
  d("BUS_EXPLORER","Bus Explorer","Submit Bus feedback","Transport",Kind.TYPE_COUNT,1,"BUS"),d("METRO_EXPLORER","Metro Explorer","Submit Metro feedback","Transport",Kind.TYPE_COUNT,1,"METRO"),d("TRAM_EXPLORER","Tram Explorer","Submit Tram feedback","Transport",Kind.TYPE_COUNT,1,"TRAM"),d("TROLLEYBUS_EXPLORER","Trolleybus Explorer","Submit Trolleybus feedback","Transport",Kind.TYPE_COUNT,1,"TROLLEYBUS"),d("NIGHT_RIDER","Night Rider","Submit Night Bus feedback","Transport",Kind.TYPE_COUNT,1,"NIGHT_BUS"),
  d("BUS_REGULAR","Bus Regular","Submit 10 Bus feedbacks","Transport",Kind.TYPE_COUNT,10,"BUS"),d("METRO_REGULAR","Metro Regular","Submit 10 Metro feedbacks","Transport",Kind.TYPE_COUNT,10,"METRO"),d("TRAM_REGULAR","Tram Regular","Submit 10 Tram feedbacks","Transport",Kind.TYPE_COUNT,10,"TRAM"),d("TROLLEYBUS_REGULAR","Trolleybus Regular","Submit 10 Trolleybus feedbacks","Transport",Kind.TYPE_COUNT,10,"TROLLEYBUS"),d("NIGHT_REGULAR","Night Regular","Submit 10 Night Bus feedbacks","Transport",Kind.TYPE_COUNT,10,"NIGHT_BUS"),
  d("GETTING_ACTIVE","Getting Active","Contribute on 3 different UTC days","Consistency",Kind.ACTIVE_DAYS,3,null),d("REGULAR_TRAVELER","Regular Traveler","Contribute on 7 different UTC days","Consistency",Kind.ACTIVE_DAYS,7,null),d("CONSISTENT_RIDER","Consistent Rider","Contribute on 15 different UTC days","Consistency",Kind.ACTIVE_DAYS,15,null),d("MONTHLY_CONTRIBUTOR","Monthly Contributor","Contribute on 30 different UTC days","Consistency",Kind.ACTIVE_DAYS,30,null),d("FREQUENT_TRAVELER","Frequent Traveler","Contribute on 60 different UTC days","Consistency",Kind.ACTIVE_DAYS,60,null),d("COMMITTED_TRAVELER","Committed Traveler","Contribute on 100 different UTC days","Consistency",Kind.ACTIVE_DAYS,100,null));
 private static Definition d(String c,String t,String x,String cat,Kind k,int n,String type){return new Definition(c,t,x,cat,k,n,type);} private AchievementCatalog(){}
}
