package com.example.crowdtransportfeedback.feedback;
import com.example.crowdtransportfeedback.common.ApiException; import com.example.crowdtransportfeedback.user.UserRepository; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*; import static com.example.crowdtransportfeedback.feedback.FeedbackDtos.*;
@Service public class FeedbackService {
 private final FeedbackRepository feedback; private final UserRepository users; FeedbackService(FeedbackRepository f,UserRepository u){feedback=f;users=u;}
 @Transactional(readOnly=true) public List<Response> all(){return feedback.findAll().stream().map(this::out).toList();}
 @Transactional(readOnly=true) public Response get(UUID id){return out(feedback.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"feedback_not_found","Feedback was not found")));}
 @Transactional public Response create(Request r,UUID userId){var found=feedback.findById(r.feedbackId());if(found.isPresent()){Feedback f=found.get();if(!f.owner.id.equals(userId)||!equivalent(f,r))throw new ApiException(HttpStatus.CONFLICT,"feedback_id_conflict","Feedback ID is already in use");return out(f);}Feedback f=new Feedback();f.feedbackId=r.feedbackId();f.owner=users.getReferenceById(userId);f.transportType=r.transportType();f.line=r.line();f.score=r.score();f.punctualityScore=r.punctualityScore();f.cleanlinessScore=r.cleanlinessScore();f.crowdingScore=r.crowdingScore();f.comment=r.comment();f.latitude=r.latitude();f.longitude=r.longitude();f.createdAt=r.createdAt();return out(feedback.save(f));}
 @Transactional public void delete(UUID id){if(!feedback.existsById(id))throw new ApiException(HttpStatus.NOT_FOUND,"feedback_not_found","Feedback was not found");feedback.deleteById(id);}
 private boolean equivalent(Feedback f,Request r){return Objects.equals(f.transportType,r.transportType())&&Objects.equals(f.line,r.line())&&f.score==r.score()&&Objects.equals(f.punctualityScore,r.punctualityScore())&&Objects.equals(f.cleanlinessScore,r.cleanlinessScore())&&Objects.equals(f.crowdingScore,r.crowdingScore())&&Objects.equals(f.comment,r.comment())&&Objects.equals(f.latitude,r.latitude())&&Objects.equals(f.longitude,r.longitude())&&f.createdAt==r.createdAt();}
 private Response out(Feedback f){return new Response(f.feedbackId,f.feedbackId.toString(),f.owner.id,f.transportType,f.line,f.score,f.punctualityScore,f.cleanlinessScore,f.crowdingScore,f.comment,f.latitude,f.longitude,f.createdAt);}
}
