package com.example.crowdtransportfeedback.auth;
import com.example.crowdtransportfeedback.common.ApiException; import com.example.crowdtransportfeedback.security.*; import com.example.crowdtransportfeedback.user.*;
import org.junit.jupiter.api.*; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import java.time.Duration; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
class AuthServiceTest {
 UserRepository users=mock(UserRepository.class); RefreshSessionRepository sessions=mock(RefreshSessionRepository.class); BCryptPasswordEncoder encoder=new BCryptPasswordEncoder(); AuthService service;
 @BeforeEach void setup(){service=new AuthService(users,sessions,encoder,new JwtService(new JwtProperties("a-secret-with-at-least-thirty-two-bytes-long",Duration.ofMinutes(5))),Duration.ofDays(90));when(users.save(any())).thenAnswer(i->i.getArgument(0));when(sessions.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void registrationCreatesUserAndHashesPassword(){var response=service.register(new AuthDtos.Credentials(" USER@Example.com ","password123"));var captor=org.mockito.ArgumentCaptor.forClass(AppUser.class);verify(users).save(captor.capture());assertEquals(Role.USER,captor.getValue().role);assertEquals("user@example.com",captor.getValue().email);assertNotEquals("password123",captor.getValue().passwordHash);assertTrue(encoder.matches("password123",captor.getValue().passwordHash));assertEquals(Role.USER,response.user().role());}
 @Test void duplicateEmailIsRejected(){when(users.existsByEmail("user@example.com")).thenReturn(true);assertThrows(ApiException.class,()->service.register(new AuthDtos.Credentials("USER@example.com","password123")));}
 @Test void validLoginSucceedsAndInvalidPasswordDoesNotRevealAccount(){var u=new AppUser(UUID.randomUUID(),"user@example.com",encoder.encode("password123"),Role.USER,java.time.Instant.now());when(users.findByEmail("user@example.com")).thenReturn(Optional.of(u));assertNotNull(service.login(new AuthDtos.Credentials("user@example.com","password123")).accessToken());assertEquals("invalid_credentials",assertThrows(ApiException.class,()->service.login(new AuthDtos.Credentials("user@example.com","wrong-pass"))).code);}
 @Test void refreshRotatesAndOldTokenCannotBeReused(){var u=new AppUser(UUID.randomUUID(),"user@example.com",encoder.encode("password123"),Role.USER,java.time.Instant.now());when(users.findByEmail("user@example.com")).thenReturn(Optional.of(u));var first=service.login(new AuthDtos.Credentials("user@example.com","password123"));var captor=org.mockito.ArgumentCaptor.forClass(RefreshSession.class);verify(sessions).save(captor.capture());var old=captor.getValue();when(sessions.findByTokenHash(AuthService.hash(first.refreshToken()))).thenReturn(Optional.of(old));var rotated=service.refresh(first.refreshToken());assertNotEquals(first.refreshToken(),rotated.refreshToken());assertNotNull(old.revokedAt);assertThrows(ApiException.class,()->service.refresh(first.refreshToken()));}
 @Test void logoutRevokesSessionAndExpiredSessionIsRejected(){var u=new AppUser(UUID.randomUUID(),"user@example.com","hash",Role.USER,java.time.Instant.now());var active=new RefreshSession(UUID.randomUUID(),u,AuthService.hash("logout-token"),java.time.Instant.now(),java.time.Instant.now().plusSeconds(60));when(sessions.findByTokenHash(active.tokenHash)).thenReturn(Optional.of(active));service.logout("logout-token");assertNotNull(active.revokedAt);var expired=new RefreshSession(UUID.randomUUID(),u,AuthService.hash("expired-token"),java.time.Instant.now().minusSeconds(120),java.time.Instant.now().minusSeconds(1));when(sessions.findByTokenHash(expired.tokenHash)).thenReturn(Optional.of(expired));assertThrows(ApiException.class,()->service.refresh("expired-token"));}
}
